server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: articleservice
            uri: http://localhost:8081/
            predicates:
              - Path=/articles
          - id: userservice
            uri: http://localhost:8082/
            predicates:
              - Path=/users, /user
